builds:
  - id: hackenv
    main: ./cmd/hackenv
    goos:
      - linux
    goarch:
      - amd64

checksum:
  algorithm: sha256

archives:
  - id: hackenv
    ids:
      - hackenv
    formats:
      - tar.gz
