builds:
  - id: hackenv
    main: ./cmd/hackenv
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/eikendev/hackenv/internal/buildconfig.Version=v{{.Version}}

checksum:
  algorithm: sha256

archives:
  - id: hackenv
    builds:
      - hackenv
    format: tar.gz
