#!/usr/bin/env bash

set -o errexit
set -o errtrace

cd "$(dirname "${BASH_SOURCE[0]}")"

archive_url='https://cdimage.kali.org/current/'
checksum_url="$archive_url/SHA256SUMS"

vmname='kali'
ifname='virbr0'
cdrom='./kali.iso'
macaddress='52:54:00:08:f9:e8'
netstatus="/var/lib/libvirt/dnsmasq/$ifname.status"

_get_ipaddress() {
	jq \
		--raw-output \
		".[] | select(.\"mac-address\"==\"$macaddress\") | .\"ip-address\"" \
		"$netstatus"
}

cmd_start() {
	virsh start "$vmname"
}

cmd_stop() {
	virsh destroy "$vmname"
}

cmd_install() {
	virt-install \
		--connect qemu:///session \
		--name "$vmname" \
		--memory 3072 \
		--vcpus 2 \
		--cpu host \
		--cdrom "$cdrom" \
		--boot cdrom \
		--os-variant debian10 \
		--nodisks \
		--filesystem "$PWD/shared,/shared" \
		--virt-type kvm \
		--network "bridge=$ifname,mac.address=$macaddress" \
		--noautoconsole
}

download_cdrom() {
	local remotename
	remotename="$1"
	curl -q -L -o "$cdrom" "$archive_url/$remotename"
}

cmd_download() {
	local remotename
	remotename="$(curl -q -s -S -L $checksum_url | grep 'live.*amd64' | awk '{ print $2 }')"

	printf "%s\n" "Found image $remotename."

	if ! [ -f "$cdrom" ]; then
		download_cdrom "$remotename"
		return 0
	fi

	read -p 'Image already exists! Do you wish to continue? [Ny]: ' -r

	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
		exit 0
	fi

	mv -f -u "$cdrom" "$cdrom.old"
	rm -f "$cdrom"

	download_cdrom "$remotename"
}

cmd_ssh() {
	local ipaddress

	ipaddress="$(_get_ipaddress)"
	printf "%s\n" "Connecting to $ipaddress."

	ssh \
		-o UserKnownHostsFile=/dev/null \
		-o StrictHostKeyChecking=no \
		"$ipaddress"
}

cmd_gui() {
	virt-viewer --connect qemu:///session "$vmname"
}

cmd_clean() {
	set +e
	cmd_stop
	set -e
	virsh undefine "$vmname"
}

cmd_list() {
	virsh list --all
}

cmd="$1"

case "$cmd" in
	start)
		cmd_start
		;;
	stop)
		cmd_stop
		;;
	install)
		cmd_install
		;;
	download)
		cmd_download
		;;
	ssh)
		cmd_ssh
		;;
	gui)
		cmd_gui
		;;
	clean)
		cmd_clean
		;;
	list)
		cmd_list
		;;
	*)
		printf "%s\n" "Usage: $0 {start,stop,install,download,ssh,gui,clean,list}" >&2
		exit 1
esac
